### ISSUE TITLE
Design a better type system and protocol for validation errors

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet#105]

**Comment by JackWilb** [comment]
I think this is done, right, @waxlamp ? We added in python typing and we're using typescript for the multinetjs. Is there any additional typing we can add to the vue components?

**Comment by waxlamp** [comment]
This issue has more to do with designing better informational object types to return from the uploader validation routines. I don't believe this is complete yet.

**Comment by waxlamp** [comment]
I believe @AlmightyYakob's (relatively) recent work on this means this issue should be closed.
