### ISSUE TITLE
Do away with separate dev and non-dev dependencies in Pipfile

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet#119]

**Comment by AlmightyYakob** [comment]
Fixed by 76fc8ac

**Comment by waxlamp** [comment]
Just FYI, @AlmightyYakob, it's a good idea to let the PR merge process close issues automatically.

**Comment by AlmightyYakob** [comment]
> Just FYI, @AlmightyYakob, it's a good idea to let the PR merge process close issues automatically.

Yeah sorry, I agree but I forgot to add that to the message in that commit.

**Comment by waxlamp** [comment]
No worries. You can also add the "closes #<...>" message directly to the PR description as well (via the edit button).

**Comment by AlmightyYakob** [comment]
> No worries. You can also add the "closes #<...>" message directly to the PR description as well (via the edit button).

Ahh, that would've been better. Thanks!
