### ISSUE TITLE
Strangeness in the routing of workspaces

### ISSUE THREAD

**Issue by jtomeck** [multinet-app/multinet#125]
The route to a workspace appears to have a bug.

For example, the path to a workspace titled "test-workspace-1" looks like this:
`/workspaces/test-workspace-1/#/workspaces/test-workspace-1/`

**Comment by jtomeck** [comment]
@waxlamp - @AlmightyYakob figured out the issue was the workspace link in #126 and suggested using vue-router for it. He's helping me fix it as we speak.

**Comment by waxlamp** [comment]
:100:

**Comment by JackWilb** [comment]
This appears to have been fixed at some point, as verified from the live app at: https://multinet.app/#/workspaces/test/.
