### ISSUE TITLE
Set up Sentry

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet#149]
I think it'd be good to setup up sentry, after we address error handling, so that any errors not caught by us that result in an internal server error are reported to Sentry.

**Comment by waxlamp** [comment]
This would be something that goes with a deployed version of the system right?

**Comment by AlmightyYakob** [comment]
Yes, and would let us catch errors in the wild. Sentry also has the functionality to report errors on the client, but I don't really think that's as important at the moment.

**Comment by JackWilb** [comment]
@AlmightyYakob Is this done with #284?

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob Is this done with #284?

Yep my bad
