### ISSUE TITLE
Less jarring selection box animation

### ISSUE THREAD

**Issue by jeffbaumes** [multinet-app/multinet#179]
Looks too flashy to me. Perhaps no transition time would look better.

![select-flashing](https://user-images.githubusercontent.com/81305/66074771-fea19b80-e527-11e9-8f9f-887a6cffe605.gif)

**Comment by waxlamp** [comment]
I think I liked no transition better too.

Sorry, @jtomeck, looks like you're officially outnumbered on this one :smile_cat:
