### ISSUE TITLE
Add pagination to table views

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet#207]
For example, the les mis data has 77 nodes and 254 edges but only shows 30 for both in the client. I assume there were plan to paginate this but it's not implemented

**Comment by waxlamp** [comment]
I can page through all 77 nodes in the les mis graph view, but not in the table view. I assume you're talking about fixing the table views to have pagination here right?

**Comment by JackWilb** [comment]
Correct

**Comment by waxlamp** [comment]
Fixed in #247
