### ISSUE TITLE
Change including .env file

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet#238]
I think it would be beneficial to instead of checking the `.env` file directly into the repository, including something like `.env.default`, (and ignoring `.env`) which contains the default values currently in `.env`. Then, the user can just copy `.env.default` to `.env`, and change any variables that need to be changed. This is a pattern I've used before in personal project and it seems to work well.

This has the benefit of working automatically with docker-compose, pipenv, etc. An example of something I currently use this for is the `ARANGO_DATA` environment variable. So instead of having to specify this everytime I run `docker-compose up`, it's just specified in the `.env` file. If this sounds good I can make these changes.

**Comment by waxlamp** [comment]
Go for it.

Would this also include a build instruction along the lines of "copy .env.example to .env, and make any necessary local changes there"?

**Comment by AlmightyYakob** [comment]
> Would this also include a build instruction along the lines of "copy .env.example to .env, and make any necessary local changes there"?

Yes it's important to highlight it in the instructions, I'll be sure to do that.
