### ISSUE TITLE
Display new page or redirect if invalid workspace name entered

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet#240]
When navigating multinet, if you enter the url of a workspace that does not exist (or perhaps that you just deleted but still have in your browser url), it will display the page as if the workspace is just empty. This could be confusing and causes problems if the user then tries to add tables (as the requests fail). A solution to this would be to display a workspace not found page, but a more immediate solution would be to simply redirect to the home page, like is already done for catching incorrect URLs.

![Screenshot from 2020-01-08 11-03-40](https://user-images.githubusercontent.com/11370025/71994428-b53ba900-3206-11ea-82e6-2a96ec0c8d7f.png)

**Comment by waxlamp** [comment]
Yikes. Good find.
