### ISSUE TITLE
Develop "downloader" architecture to allow for getting tables and graphs

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet#258]
This would/could be a counterpart to our "uploader" architecture (but not a one-to-one correspondence). For instance, downloading graphs in a variety of common formats would be great, but downloading table data in just CSV and JSON is probably good enough.

**Comment by AlmightyYakob** [comment]
Should this be closed since #262 was merged?

**Comment by waxlamp** [comment]
Yup.
