### ISSUE TITLE
Include branch name alongside SHA display

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet#267]
The client displays which Git SHA (i.e., commit) it was built from in the about panel. It might be beneficial to also display the branch name with that commit information.

**Comment by JackWilb** [comment]
Would this not always just be master? Unless it's built locally, but at the stage you could check in the terminal, right?

**Comment by waxlamp** [comment]
It would usually be master, and you are right, this is not particularly useful information. I will close, and if someone disagrees they can reopen.
