### ISSUE TITLE
Can't start the test server on mac

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet#268]
The docker tries to bind to /var/ which throws an error on mac. This isn't mission critical but would be nice to fix going forward

**Comment by AlmightyYakob** [comment]
Is this the same issue addressed in step 5 of the [installation docs](https://multinet-girder.readthedocs.io/en/latest/installation.html)?

**Comment by JackWilb** [comment]
Ahh, looks like it. Let me test and report back

**Comment by JackWilb** [comment]
So not quite. The error is: 

>ERROR: for testing_arangodb_1  Cannot start service arangodb: b'Mounts denied: \r\nThe paths /var/arangodb and /var/arangodb-apps\r\nare not shared from OS X and are not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.' 
ERROR: for arangodb  Cannot start service arangodb: b'Mounts denied: \r\nThe paths /var/arangodb and /var/arangodb-apps\r\nare not shared from OS X and are not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'

**Comment by JackWilb** [comment]
There's also an error with readfile:

> readlink: illegal option -- f
usage: readlink [-n] [file ...]

**Comment by JackWilb** [comment]
It works if you remove the ARANGO_DATA definitions on line 14 of scripts/start.sh

**Comment by JackWilb** [comment]
The error is actually in the command `pipenv run test-server-up`.

The command calls out to scripts/server/start.sh, which uses readlink on line 14. The problem is that mac uses the bsd implementation of readline, which has substantive differences to the linux version, so the command doesn't run. I've attached a screenshot of the start up process here. It looks like readlink fails so it just uses the default paths in /var/.

![Screen Shot 2020-02-12 at 12 40 15 PM](https://user-images.githubusercontent.com/36867477/74370750-86998b00-4dcf-11ea-8711-523727793a1e.png)

One solution could be to use a directory in the home folder, but that's messy. We could require that /var is shared with docker from macOS, but that would leave remnants in the future.

**Comment by waxlamp** [comment]
But you don't need to use `test-server-up` anymore right? Local testing is now done through the dev server, so if `pipenv run serve` is working then you should be good to go.

**Comment by JackWilb** [comment]
Since it's now using 8080 and 5000, yes you can just run the main version of the apps. You can't quite run the same steps as in the yaml for testing, but that should be fine
