### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multinet#273]
* [ ] Add the MultiNet Logo in the top left corner 
 * [ ] Create a more extensive about page, @alexsb  can provide content if it's set up. We should discuss whether the pop-up is enough or whether that's just version info. 
 * [ ] Add Utah, Kitware, and NSF logo to front page; in a muted color.

**Comment by waxlamp** [comment]
Closing in favor of #286, #287, and #288.
