### ISSUE TITLE
Allow deleting datasets and workspaces

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multinet#276]

**Comment by waxlamp** [comment]
This is actually already done, but perhaps not very discoverable.

To delete a workspace, hover over the workspace name in the left sidebar, then click on the checkbox. This will cause a trash icon to appear in the top of the sidebar, which leads to a confirmation dialog for deletion. Of course, multiple workspaces can be deleted at once by clicking on several checkboxes.

There is a very similar mechanism for deleting both tables and networks in the "workspace detail" view (after clicking on a workspace to select it from the sidebar).

I will open a new issue for making this UI affordance more obvious/discoverable, but I think we should defer work on it until after the demo. Let me know if you agree with that plan, @alexsb.

**Comment by waxlamp** [comment]
Closing in favor of #293.
