### ISSUE TITLE
Data Upload Master Issue

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multinet#277]
There should be two ways to upload a network: 

 * Upload a network file, such as a nested json or a d3-style json. This should create the network, a table for each node type, and a table for each edge type. No further assembly should be required. The initial data formats should be the d3-style json gefx: and https://gephi.org/gexf/format/
 * Upload a table of nodes and links from CSV. In a next step, I want to manually assemble how to link up the nodes based on the keys.

**Comment by waxlamp** [comment]
> There should be two ways to upload a network:
> 
> * Upload a network file, such as a nested json or a d3-style json. This should create the network, a table for each node type, and a table for each edge type. No further assembly should be required. The initial data formats should be the d3-style json gefx: and https://gephi.org/gexf/format/

Agreed.

> * Upload a table of nodes and links from CSV. In a next step, I want to manually assemble how to link up the nodes based on the keys.

Do you mean to somehow upload both nodes and links from a single CSV? Or just upload a node table, then an edge table, then decide how and when to create the network?

**Comment by alexsb** [comment]
Re both nodes and links: probably not, unless it's a specific file format. Otherwise that would be a mess.

**Comment by waxlamp** [comment]
> Re both nodes and links: probably not, unless it's a specific file format. Otherwise that would be a mess.

This is what I thought, just wanted to make sure.
