### ISSUE TITLE
Provide Context for File Formats when uploading

### ISSUE THREAD

**Issue by alexsb** [multinet-app/multinet#282]
Since we have a few non-standard file formats that we want to read, we might have to give a little context. This is the current state: 

![image](https://user-images.githubusercontent.com/2039375/73495927-b2028b80-4374-11ea-89e6-6eef94e89552.png)

 * [x] The drop down should be descriptive. For example, instead of newick, it should be "Newick, Tree format, Ext: .csv, .tsv, .txt" 
 * [x] After I've selected the drop-down, we want to show a bit of text about the file format below. That could be as simple as "gefx, The [Gephi Network File Format](https://gephi.org/gexf/format/)" (with the link); or as verbose as "D3-Style Json Network Format"  followed by an actual example.

**Comment by jtomeck** [comment]
@waxlamp do you know if hyperlinks work within Vuetify's select component? If not, it might make sense for a message to be displayed underneath the field in a small font after you select the type.

**Comment by waxlamp** [comment]
> @waxlamp do you know if hyperlinks work within Vuetify's select component? If not, it might make sense for a message to be displayed underneath the field in a small font after you select the type.

I think it's better to have the description show up below, as you mentioned. The dropdown will just have the "name" of the option (along the lines Alex described).
