### ISSUE TITLE
Integration tests need a timeout

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet#294]
The integration tests will simply hang if something goes wrong. For instance, if a test is waiting for a specific element to show up, and it never does (due to, say, a change in the code), then the test will simply run forever. Instead, we should have some reasonable time limit (perhaps 60 seconds) after which the test should simply fail so the suite can move on.

**Comment by JackWilb** [comment]
Is this in reference to this failed run: https://github.com/multinet-app/multinet/runs/424002767?

**Comment by waxlamp** [comment]
> Is this in reference to this failed run: https://github.com/multinet-app/multinet/runs/424002767?

Yeah, because I had changed one of the expected pieces of DOM for that test, the test just hung.
